/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TalentRouteImport } from './routes/talent'
import { Route as PoliticaPrivacidadRouteImport } from './routes/politica-privacidad'
import { Route as FootprintRouteImport } from './routes/footprint'
import { Route as DesarrolloTecnologicoRouteImport } from './routes/desarrollo-tecnologico'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConsultoriaEstrategicaRouteImport } from './routes/consultoria-estrategica'
import { Route as BoardRouteImport } from './routes/board'
import { Route as AvisoLegalRouteImport } from './routes/aviso-legal'
import { Route as AutomatizacionProcesosRouteImport } from './routes/automatizacion-procesos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesEngineeringRouteImport } from './routes/services.engineering'
import { Route as ServicesEnergyRouteImport } from './routes/services.energy'
import { Route as ServicesBpoRouteImport } from './routes/services.bpo'
import { Route as ServicesAssetManagementRouteImport } from './routes/services.asset-management'

const TalentRoute = TalentRouteImport.update({
  id: '/talent',
  path: '/talent',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaPrivacidadRoute = PoliticaPrivacidadRouteImport.update({
  id: '/politica-privacidad',
  path: '/politica-privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const FootprintRoute = FootprintRouteImport.update({
  id: '/footprint',
  path: '/footprint',
  getParentRoute: () => rootRouteImport,
} as any)
const DesarrolloTecnologicoRoute = DesarrolloTecnologicoRouteImport.update({
  id: '/desarrollo-tecnologico',
  path: '/desarrollo-tecnologico',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultoriaEstrategicaRoute = ConsultoriaEstrategicaRouteImport.update({
  id: '/consultoria-estrategica',
  path: '/consultoria-estrategica',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisoLegalRoute = AvisoLegalRouteImport.update({
  id: '/aviso-legal',
  path: '/aviso-legal',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomatizacionProcesosRoute = AutomatizacionProcesosRouteImport.update({
  id: '/automatizacion-procesos',
  path: '/automatizacion-procesos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesEngineeringRoute = ServicesEngineeringRouteImport.update({
  id: '/services/engineering',
  path: '/services/engineering',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesEnergyRoute = ServicesEnergyRouteImport.update({
  id: '/services/energy',
  path: '/services/energy',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesBpoRoute = ServicesBpoRouteImport.update({
  id: '/services/bpo',
  path: '/services/bpo',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAssetManagementRoute = ServicesAssetManagementRouteImport.update({
  id: '/services/asset-management',
  path: '/services/asset-management',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/automatizacion-procesos': typeof AutomatizacionProcesosRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/board': typeof BoardRoute
  '/consultoria-estrategica': typeof ConsultoriaEstrategicaRoute
  '/contact': typeof ContactRoute
  '/desarrollo-tecnologico': typeof DesarrolloTecnologicoRoute
  '/footprint': typeof FootprintRoute
  '/politica-privacidad': typeof PoliticaPrivacidadRoute
  '/talent': typeof TalentRoute
  '/services/asset-management': typeof ServicesAssetManagementRoute
  '/services/bpo': typeof ServicesBpoRoute
  '/services/energy': typeof ServicesEnergyRoute
  '/services/engineering': typeof ServicesEngineeringRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/automatizacion-procesos': typeof AutomatizacionProcesosRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/board': typeof BoardRoute
  '/consultoria-estrategica': typeof ConsultoriaEstrategicaRoute
  '/contact': typeof ContactRoute
  '/desarrollo-tecnologico': typeof DesarrolloTecnologicoRoute
  '/footprint': typeof FootprintRoute
  '/politica-privacidad': typeof PoliticaPrivacidadRoute
  '/talent': typeof TalentRoute
  '/services/asset-management': typeof ServicesAssetManagementRoute
  '/services/bpo': typeof ServicesBpoRoute
  '/services/energy': typeof ServicesEnergyRoute
  '/services/engineering': typeof ServicesEngineeringRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/automatizacion-procesos': typeof AutomatizacionProcesosRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/board': typeof BoardRoute
  '/consultoria-estrategica': typeof ConsultoriaEstrategicaRoute
  '/contact': typeof ContactRoute
  '/desarrollo-tecnologico': typeof DesarrolloTecnologicoRoute
  '/footprint': typeof FootprintRoute
  '/politica-privacidad': typeof PoliticaPrivacidadRoute
  '/talent': typeof TalentRoute
  '/services/asset-management': typeof ServicesAssetManagementRoute
  '/services/bpo': typeof ServicesBpoRoute
  '/services/energy': typeof ServicesEnergyRoute
  '/services/engineering': typeof ServicesEngineeringRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/automatizacion-procesos'
    | '/aviso-legal'
    | '/board'
    | '/consultoria-estrategica'
    | '/contact'
    | '/desarrollo-tecnologico'
    | '/footprint'
    | '/politica-privacidad'
    | '/talent'
    | '/services/asset-management'
    | '/services/bpo'
    | '/services/energy'
    | '/services/engineering'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/automatizacion-procesos'
    | '/aviso-legal'
    | '/board'
    | '/consultoria-estrategica'
    | '/contact'
    | '/desarrollo-tecnologico'
    | '/footprint'
    | '/politica-privacidad'
    | '/talent'
    | '/services/asset-management'
    | '/services/bpo'
    | '/services/energy'
    | '/services/engineering'
  id:
    | '__root__'
    | '/'
    | '/automatizacion-procesos'
    | '/aviso-legal'
    | '/board'
    | '/consultoria-estrategica'
    | '/contact'
    | '/desarrollo-tecnologico'
    | '/footprint'
    | '/politica-privacidad'
    | '/talent'
    | '/services/asset-management'
    | '/services/bpo'
    | '/services/energy'
    | '/services/engineering'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutomatizacionProcesosRoute: typeof AutomatizacionProcesosRoute
  AvisoLegalRoute: typeof AvisoLegalRoute
  BoardRoute: typeof BoardRoute
  ConsultoriaEstrategicaRoute: typeof ConsultoriaEstrategicaRoute
  ContactRoute: typeof ContactRoute
  DesarrolloTecnologicoRoute: typeof DesarrolloTecnologicoRoute
  FootprintRoute: typeof FootprintRoute
  PoliticaPrivacidadRoute: typeof PoliticaPrivacidadRoute
  TalentRoute: typeof TalentRoute
  ServicesAssetManagementRoute: typeof ServicesAssetManagementRoute
  ServicesBpoRoute: typeof ServicesBpoRoute
  ServicesEnergyRoute: typeof ServicesEnergyRoute
  ServicesEngineeringRoute: typeof ServicesEngineeringRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/talent': {
      id: '/talent'
      path: '/talent'
      fullPath: '/talent'
      preLoaderRoute: typeof TalentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-privacidad': {
      id: '/politica-privacidad'
      path: '/politica-privacidad'
      fullPath: '/politica-privacidad'
      preLoaderRoute: typeof PoliticaPrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/footprint': {
      id: '/footprint'
      path: '/footprint'
      fullPath: '/footprint'
      preLoaderRoute: typeof FootprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desarrollo-tecnologico': {
      id: '/desarrollo-tecnologico'
      path: '/desarrollo-tecnologico'
      fullPath: '/desarrollo-tecnologico'
      preLoaderRoute: typeof DesarrolloTecnologicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultoria-estrategica': {
      id: '/consultoria-estrategica'
      path: '/consultoria-estrategica'
      fullPath: '/consultoria-estrategica'
      preLoaderRoute: typeof ConsultoriaEstrategicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aviso-legal': {
      id: '/aviso-legal'
      path: '/aviso-legal'
      fullPath: '/aviso-legal'
      preLoaderRoute: typeof AvisoLegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automatizacion-procesos': {
      id: '/automatizacion-procesos'
      path: '/automatizacion-procesos'
      fullPath: '/automatizacion-procesos'
      preLoaderRoute: typeof AutomatizacionProcesosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/engineering': {
      id: '/services/engineering'
      path: '/services/engineering'
      fullPath: '/services/engineering'
      preLoaderRoute: typeof ServicesEngineeringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/energy': {
      id: '/services/energy'
      path: '/services/energy'
      fullPath: '/services/energy'
      preLoaderRoute: typeof ServicesEnergyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/bpo': {
      id: '/services/bpo'
      path: '/services/bpo'
      fullPath: '/services/bpo'
      preLoaderRoute: typeof ServicesBpoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/asset-management': {
      id: '/services/asset-management'
      path: '/services/asset-management'
      fullPath: '/services/asset-management'
      preLoaderRoute: typeof ServicesAssetManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutomatizacionProcesosRoute: AutomatizacionProcesosRoute,
  AvisoLegalRoute: AvisoLegalRoute,
  BoardRoute: BoardRoute,
  ConsultoriaEstrategicaRoute: ConsultoriaEstrategicaRoute,
  ContactRoute: ContactRoute,
  DesarrolloTecnologicoRoute: DesarrolloTecnologicoRoute,
  FootprintRoute: FootprintRoute,
  PoliticaPrivacidadRoute: PoliticaPrivacidadRoute,
  TalentRoute: TalentRoute,
  ServicesAssetManagementRoute: ServicesAssetManagementRoute,
  ServicesBpoRoute: ServicesBpoRoute,
  ServicesEnergyRoute: ServicesEnergyRoute,
  ServicesEngineeringRoute: ServicesEngineeringRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
